### PR TITLE
[test] Fix handleHybridOverlay()

### PR DESCRIPTION
**Pull request by aravindhp**
Sync up to match up with how we are [configuring hybrid-overlay in WMCO](https://github.com/openshift/windows-machine-config-operator/blob/a094884abffac047c1199dce1281969a1e320682/pkg/windows/windows.go#L362):
- Add a sleep to wait for the network reconfiguration to complete
- Change the ordering of reinitialization of the SSH connection
- Remove a stale comment which is remnant of the WNI / WinRM days

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
Changes LGTM.
Do we still need to run hybrid overlay in the [background](https://github.com/openshift/windows-machine-config-bootstrapper/blob/0d5d2f4fce523dfb6978b78c64705c9a123836ea/internal/test/wmcb/wmcb_test.go#L234), was the reason for doing that because we weren't doing this reinitialization or will that require further investigation?

**Comment by saifshaikh48** [comment]
/lgtm
/hold

Hold for Mansi's question above.

**Comment by aravindhp** [comment]
> Changes LGTM.
> Do we still need to run hybrid overlay in the [background](https://github.com/openshift/windows-machine-config-bootstrapper/blob/0d5d2f4fce523dfb6978b78c64705c9a123836ea/internal/test/wmcb/wmcb_test.go#L234), was the reason for doing that because we weren't doing this reinitialization or will that require further investigation?

@mansikulkarni96, yes we need still need to run hybrid-overlay in the background or as a service. That is what happens when you run it as a service like we are doing in WMCO. I don't fully understand rest of the question though. We were always doing the re initialization but in a different order.

**Comment by mansikulkarni96** [comment]
Thanks for the explanation @aravindhp my question came from the comment [here](https://github.com/openshift/windows-machine-config-bootstrapper/blob/0d5d2f4fce523dfb6978b78c64705c9a123836ea/internal/test/wmcb/wmcb_test.go#L231). But I now realize that comment is dated and might not be relevant to the current code.

**Comment by aravindhp** [comment]
Ah yes, that comment is outdated. I can remove it. as part of this PR.

**Comment by mansikulkarni96** [comment]
Thanks for fixing this.
/lgtm

**Pull request merged**
