### PR TITLE
[Dockerfile] Update WMCO branch to community-4.9

### PR DESCRIPTION
**Pull request by aravindhp**
React to upstream CNI changes:
- [build] Install dos2unix for building CNI plugins
    Ref: openshift/containernetworking-plugins@623f148
- [build][windows][nodeconfig] Remove flannel.exe
    Ref: openshift/containernetworking-plugins@77233dd

### CODE REVIEW

**Review by selansen — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
/hold
waiting on #321

**Pull request merged**
