### PR TITLE
[docs] Convert WinC Azure docs to Markdown

### PR DESCRIPTION
**Pull request by codyhoag**
The initial conversion from Google Doc → Markdown. I plan to followup with some wordsmithing at a later date.

### CODE REVIEW

**Comment by codyhoag** [comment]
I will squash commits once reviews have finalized. I wanted to preserve the changes based off the original doc.

**Comment by aravindhp** [comment]
@codyhoag, @Anandnatraj has approved so please squash your commits. I will approve and get it merged.

**Comment by codyhoag** [comment]
@aravindhp They're now squashed. Thanks!

**Pull request merged**
