### PR TITLE
Bug 1924039: [vendor] Update to github.com/gogo/protobuf:v1.3.2

### PR DESCRIPTION
**Pull request by saifshaikh48**
Ran:
- `go get "github.com/gogo/protobuf"`
- `go mod tidy && go mod vendor`

Fixes rhbz#1924039

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/retest e2e-wmcb

cluster spin-up failure

**Review by selansen — APPROVED** [review]
/lgtm

**Pull request merged**
