### PR TITLE
[test] Fix windows.Run()

### PR DESCRIPTION
**Pull request by aravindhp**
- Fix returning the output when the command returned an error
- Gracefully handle closing a session that has already been closed

### CODE REVIEW

**Comment by jrvaldes** [comment]
/lgtm

May need rebase once https://github.com/openshift/windows-machine-config-bootstrapper/pull/279 merges.

**Comment by aravindhp** [comment]
/retitle WIP: [test] Fix error output not being shown in logs

**Comment by aravindhp** [comment]
/retest

cluster creation failure

**Comment by aravindhp** [comment]
/retest

TestKubeletUninstall e2e failed

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
Getting a slightly different [error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-bootstrapper/276/pull-ci-openshift-windows-machine-config-bootstrapper-master-e2e-wmcb/1428412850170236928) now:

```
     wmcb_test.go:155: 
        	Error Trace:	wmcb_test.go:155
        	            				wmcb_test.go:115
        	            				wmcb_test.go:105
        	Error:      	Received unexpected error:
        	            	error running hybrid-overlay-node.exe: timeout waiting for hybrid-overlay-node: read tcp 10.0.173.118:54376->10.0.158.79:22: read: connection timed out
        	Test:       	TestWMCB/E2E
        	Messages:   	unable to handle hybrid-overlay 
```
I wonder if this is actual infra issue. 

Also noticing `2021/08/19 19:02:19 warning - error closing ssh client connection: close tcp 10.0.173.118:54376->10.0.158.79:22: use of closed network connection` which I know how to fix.

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Pull request merged**
