### PR TITLE
[release 4.10] WINC-923: bumps pause image to 3.9

### PR DESCRIPTION
**Pull request by wgahnagl**
gets pause image up to date for bootstrapper

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
There are likely unit tests that need to be updated like you did in [the 4.9 PR](https://github.com/openshift/windows-machine-config-bootstrapper/pull/368/files#diff-c28fa61c93e3f117dea1a808854d6b9309175dc85d833e2a67b6e33ff2d92bfa). You can run them locally to make sure they pass

**Review by aravindhp — APPROVED** [review]
Thanks for working on this, @wgahnagl

**Comment by aravindhp** [comment]
/retitle [release 4.10] WINC-923: bumps pause image to 3.9

**Comment by aravindhp** [comment]
> There are likely unit tests that need to be updated like you did in [the 4.9 PR](https://github.com/openshift/windows-machine-config-bootstrapper/pull/368/files#diff-c28fa61c93e3f117dea1a808854d6b9309175dc85d833e2a67b6e33ff2d92bfa). You can run them locally to make sure they pass

That's a good point, @saifshaikh48. @wgahnagl this means that you will not be able to cherry-pick the change.

/approve cancel

**Review by aravindhp — APPROVED** [review]
Thanks for working on this, @wgahnagl

**Comment by aravindhp** [comment]
> > There are likely unit tests that need to be updated like you did in [the 4.9 PR](https://github.com/openshift/windows-machine-config-bootstrapper/pull/368/files#diff-c28fa61c93e3f117dea1a808854d6b9309175dc85d833e2a67b6e33ff2d92bfa). You can run them locally to make sure they pass
> 
> That's a good point, @saifshaikh48. @wgahnagl this means that you will not be able to cherry-pick the change.

I am wrong about this. Cherry pick should be possible.

**Pull request merged**
