### PR TITLE
[wmcb] revert vendordiff.patch

### PR DESCRIPTION
**Pull request by mansikulkarni96**
Reverting addition of vendordiff.patch that was merged as a part of adding
vendor directories and script in https://github.com/openshift/windows-machine-config-bootstrapper/pull/230

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Thanks @mansikulkarni96  for working on this

/lgtm

**Review by aravindhp — APPROVED** [review]
/approve

Thanks for fixing this, @mansikulkarni96

**Pull request merged**
