### PR TITLE
WINC-479: [wni] Remove wni from bootstrapper

### PR DESCRIPTION
**Pull request by VaishnaviHire**
This commit ensures that all unused wni code is
deleted and is not used by any other component.

### CODE REVIEW

**Review by aravindhp — CHANGES_REQUESTED** [review]
Thanks for working on this @VaishnaviHire. You also need to remove `make build-tools` in the [release config](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master.yaml#L38).

**Comment by VaishnaviHire** [comment]
[PR](https://github.com/openshift/release/pull/14570) for removing `make build-tools`

**Review by aravindhp — APPROVED** [review]
/approve

**Pull request merged**
