### PR TITLE
[release 4.9] WINC-923: bumps pause image to 3.9

### PR DESCRIPTION
**Pull request by wgahnagl**
gets pause image up to date for bootstrapper on 4.9

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by aravindhp** [comment]
@wgahnagl you should be using the cherry-pick bot to open this PR from https://github.com/openshift/windows-machine-config-bootstrapper/pull/369

**Comment by aravindhp** [comment]
/retitle [release 4.9] WINC-923: bumps pause image to 3.9

**Review by aravindhp — APPROVED** [review]
@wgahnagl. Let us get this merged and fixed in order. i.e. release-4.10 first and then release-4.9. The reason for this is we don't want to potentially cut a 4.9 release with code that is not present in 4.10.

**Pull request closed without merging**
